POST https://localhost:5050/products
Content-Type: application/json

{
    "Name": "Product 1",
    "Description": "Product A - description",
    "ImageFile" : "Image file path",
    "Price" : 1.0,
    "Category": ["c1", "c2"]
}