# version: '3.4'

services:
  eshop.catalogdb:
    image: postgres

  eshop.basketdb:
    image: postgres

  eshop.distributedcache:
    image: redis

  eshop.orderdb:
    image: mcr.microsoft.com/mssql/server

  eshop.messagebroker:
    image: rabbitmq:management

  eshop.catalog.api:
    image: ${DOCKER_REGISTRY-}catalogapi
    build:
      context: .
      dockerfile: Services/Catalog/Catalog.API/Dockerfile

  eshop.basket.api:
    image: ${DOCKER_REGISTRY-}basketapi
    build:
      context: .
      dockerfile: Services/Basket/Basket.API/Dockerfile

  eshop.discount.grpc:
    image: ${DOCKER_REGISTRY-}discountgrpc
    build:
      context: .
      dockerfile: Services/Discount/Discount.gRPC/Dockerfile

  eshop.order.api:
    image: ${DOCKER_REGISTRY-}orderapi
    build:
      context: .
      dockerfile: Services/Order/Order.API/Dockerfile

  eshop.apigw.yarp:
    image: ${DOCKER_REGISTRY-}yarpapigateway
    build:
      context: .
      dockerfile: APIGateways/YarpApiGateway/Dockerfile

volumes:
  postgres_catalog:
  postgres_basket:
  mssql_orderdb:

networks:
  eshop_network:    
    name: eshop.network
    driver: bridge
