# version: '3.4'

services:
# Postgres - CatalogDb
 catalogdb:
   container_name: eshop.catalogdb
   environment:
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=postgres
    - POSTGRES_DB=CatalogDb
   restart: always
   ports:
    - "5432:5432"
   volumes:
    - postgres_catalog:/var/lib/postgresql/data/
   networks:
    - eshop_network

# Postgres - BasketDb 
 basketdb:
   container_name: eshop.basketdb
   environment:
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=postgres
    - POSTGRES_DB=BasketDb
   restart: always
   ports:
    - "5433:5432"
   volumes:
    - postgres_basket:/var/lib/postgresql/data/
   networks:
    - eshop_network

# Redis Cache - distributedcache
 distributedcache:
   container_name: eshop.distributedcache
   ports:
    - "6379:6379"
   restart: always
   networks:
    - eshop_network

# MS SQL - orderDb
 orderdb:
   container_name: eshop.orderdb
   environment:
     - ACCEPT_EULA=Y
     - SA_PASSWORD=Sql!Dev12
   restart: always 
   ports:
     - "1433:1433"
   volumes:
     - mssql_orderdb:/var/lib/mssql/data/
   networks:
    - eshop_network

# Messagebroker - RabbitMq
 eshop.messagebroker:
    container_name: eshop.messagebroker
    hostname: ecommerce-mq
    environment:
        - RABBITMQ_DEFAULT_USER=guest
        - RABBITMQ_DEFAULT_PASS=guest
    restart: always
    ports:
        - "5670:5672"
        - "15670:15672"
    networks:
    - eshop_network

# API - Catalog MicroService
 catalog.api:
    container_name: eshop.catalog.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      - ConnectionStrings__Database=Server=catalogdb;Port=5432;Database=CatalogDb;User Id=postgres;Password=postgres;Include Error Detail=true
    depends_on:
      - catalogdb
    ports:
      - "6000:8080"
      - "6060:8081"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
    networks:
      - eshop_network

# API - Basket MicroService
 basket.api:
    container_name: eshop.basket.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      - ConnectionStrings__Database=Server=basketdb;Port=5432;Database=BasketDb;User Id=postgres;Password=postgres;Include Error Detail=true
      - ConnectionStrings__Redis=eshop.distributedcache:6379,abortConnect=false
      - GrpcSettings__DiscountUri=https://discount.grpc:8081
    depends_on:
      - basketdb
      - distributedcache
      - discount.grpc
    ports:
      - "6001:8080"
      - "6061:8081"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
    networks:
      - eshop_network

# Discount.Grpc MicroService
 discount.grpc:
    container_name: eshop.discount.grpc
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      - ConnectionStrings__Database=Data Source=eshop.discount.db
    ports:
      - "6002:8080"
      - "6062:8081"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
    networks:
      - eshop_network