## GET Basket for a user
GET {{BasketAPI_baseUrl}}/basket/User_1
Content-Type: application/json
###

POST {{BasketAPI_baseUrl}}/basket
Content-Type: application/json

{
    "Cart": {
        "UserName": "User_1",
        "Items": [
            {
                "ProductId": "5334c996-8457-4cf0-815c-ed2b77c4ff61",
                "ProductName": "IPhone X",            
                "Color": "Red",
                "Quantity": 2,
                "Price": 500
            }
        ]
    }
}
###

DELETE {{BasketAPI_baseUrl}}/basket/dummy
Content-Type: application/json

###