###
## Create Product
POST https://localhost:6050/products
Content-Type: application/json

{
    "Name" : "Product 1",
    "Description" : "First product description", 
    "ImageFile" : "First product image file path",
    "Price" : 2,
    "Category": ["p1", "p2"]
}
###

## GET Products List
GET https://localhost:6050/products
Content-Type: application/json

###

## GET Product by Id
GET https://localhost:6050/products/01948fa7-bdc8-4968-b039-7c5ac79aafb2
Content-Type: application/json

###

## GET Product by Category
GET https://localhost:6050/products/category/p2
Content-Type: application/json

###