###
## Create Product
POST {{baseUrl}}/products
Content-Type: application/json

{
    "Name" : "Product 1",
    "Description" : "First product description", 
    "ImageFile" : "First product image file path",
    "Price" : 2.0,
    "Category": ["p1", "p2"]
}
###

## GET Products List
GET {{baseUrl}}/products
?pageNumber=4
&pageSize=2
Content-Type: application/json
###

## GET Product by Id
GET {{baseUrl}}/products/019515b8-7216-4ed4-b82c-e15b9c6b8d00
Content-Type: application/json

###

## GET Product by Category
GET {{baseUrl}}/products/category/Camera
# ?pageNumber=1
# &pageSize=2
# &category=Camera
Content-Type: application/json

###

## PUT Product by Id
PUT {{baseUrl}}/products
Content-Type: application/json

{
    "id": "01948619-4e97-4f4f-af4e-249663337222",
    "name": "Product #1",
    "description": "Product #1 description",
    "imageFile": "image not available",
    "price": 2.5,
    "category": [
    "Prd1",
    "Prd2"
    ]
}
###

## DELETE Product by Id
DELETE {{baseUrl}}/products/01948fa8-61e4-4c1c-807e-560b491fbb1c
Content-Type: application/json

###

## GET Health of the microservice
GET {{baseUrl}}/health
# ?pageNumber=4
# &pageSize=2
Content-Type: application/json
###